# Generated by Django 5.1.4 on 2025-02-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstate',
            name='link_admission',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
