# Generated by Django 5.1.3 on 2025-01-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroequipe',
            name='areaUsuario',
            field=models.CharField(max_length=20),
        ),
    ]
