# Generated by Django 5.1.4 on 2025-02-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_membroequipe_areausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroequipe',
            name='areaUsuario',
        ),
    ]
