# Generated by Django 5.1.3 on 2025-01-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_membroequipe_areausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroequipe',
            name='areaUsuario',
            field=models.CharField(choices=[('SE', 'Engenharia de Software'), ('DS', 'Ciência de Dados'), ('DO', 'DevOps'), ('UX', 'UI/UX Design')], default='SE', max_length=2),
        ),
    ]
