# Generated by Django 5.1.3 on 2025-01-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_membroequipe_areausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='testearea',
            field=models.ManyToManyField(blank=True, related_name='area', to='Users.area'),
        ),
    ]
