# Generated by Django 5.1.3 on 2025-02-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_membroequipe_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroequipe',
            name='areaUsuario',
        ),
    ]
