# Generated by Django 5.1.4 on 2025-02-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_membroequipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membroequipe',
            old_name='testearea',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='areas',
        ),
    ]
