# Generated by Django 5.1.4 on 2025-01-23 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_membroequipe_testearea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroequipe',
            name='testearea',
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='Users.area'),
        ),
    ]
