# Generated by Django 5.1.3 on 2024-12-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_area_function_membroequipe_areas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('nome_equipe_registradora', models.TextField()),
                ('funcao_equipe_registradora', models.TextField()),
                ('membros_envolvidos', models.TextField()),
                ('local_problema', models.TextField()),
                ('explicacao_detalhada', models.TextField()),
                ('codigo_peca_danificada', models.CharField(max_length=50)),
                ('velocidade_m_s', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direcao_vento', models.CharField(max_length=50)),
                ('pressao_atmosferica_hpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_decolagem_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_voos_piloto', models.IntegerField()),
                ('impressoes_piloto', models.TextField()),
                ('telemetria_link', models.URLField()),
                ('foto_pecas_danificadas_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('papel', models.CharField(choices=[('Admin', 'Administrador'), ('Piloto', 'Piloto'), ('Trainee', 'Trainee'), ('Usuario', 'Usuário')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('nome_piloto', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('membros_envolvidos', models.TextField()),
                ('nivel_sucesso', models.PositiveSmallIntegerField()),
                ('descricao_objetivo', models.TextField()),
                ('exito', models.TextField()),
                ('impressoes_piloto', models.TextField()),
                ('melhorias', models.TextField()),
                ('velocidade_m_s', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direcao_vento', models.CharField(max_length=50)),
                ('pressao_atmosferica_hpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_decolagem_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ciclos_voo', models.IntegerField()),
                ('telemetria_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluída', 'Concluída')], max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usuario')),
            ],
        ),
    ]
