# Generated by Django 5.1.4 on 2025-01-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_membroequipe_testearea_membroequipe_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroequipe',
            name='area',
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='testearea',
            field=models.ManyToManyField(blank=True, related_name='area', to='Users.area'),
        ),
    ]
