# Generated by Django 5.1.4 on 2025-02-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_membroequipe_areausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroequipe',
            name='testearea',
        ),
    ]
