# Generated by Django 5.1.4 on 2025-02-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_testearea_membroequipe_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='membros', to='Users.area'),
        ),
    ]
