# Generated by Django 5.1.3 on 2024-12-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_produto_registroacidente_usuario_voo_tarefa_ata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voo',
        ),
    ]
