# Generated by Django 5.1 on 2025-02-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_position_function_priority_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='area', to='Users.area'),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='areaUsuario',
            field=models.CharField(choices=[('SE', 'Engenharia de Software'), ('DS', 'Ciência de Dados'), ('DO', 'DevOps'), ('UX', 'UI/UX Design')], default='SE', max_length=2),
        ),
    ]
