# Generated by Django 5.1.4 on 2025-01-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_membroequipe_areas_membroequipe_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
