# Generated by Django 5.1 on 2025-01-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_membroequipe_areas_membroequipe_functions'),
        ('Users', '0009_membroequipe_photo'),
    ]

    operations = [
    ]
