# Generated by Django 5.1 on 2025-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_merge_20250119_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroequipe',
            name='photo',
            field=models.ImageField(blank=True, default='fotos_membros/default.png', null=True, upload_to='fotos_membros/'),
        ),
    ]
