# Generated by Django 5.1 on 2025-01-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_area_color'),
        ('Users', '0011_alter_membroequipe_photo'),
    ]

    operations = [
    ]
