# Generated by Django 5.1.3 on 2024-12-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('nome_piloto', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('membros_envolvidos', models.TextField()),
                ('nivel_sucesso', models.PositiveSmallIntegerField()),
                ('descricao_objetivo', models.TextField()),
                ('exito', models.TextField()),
                ('impressoes_piloto', models.TextField()),
                ('melhorias', models.TextField()),
                ('velocidade_m_s', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direcao_vento', models.CharField(max_length=50)),
                ('pressao_atmosferica_hpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_decolagem_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ciclos_voo', models.IntegerField()),
                ('telemetria_link', models.URLField()),
            ],
        ),
    ]
