# Generated by Django 5.1 on 2025-02-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='area',
            new_name='areas',
        ),
    ]
