# Generated by Django 5.1 on 2025-02-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
