# Generated by Django 5.1.3 on 2025-01-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='area',
            field=models.CharField(choices=[('SE', 'Engenharia de Software'), ('DS', 'Ciência de Dados'), ('DO', 'DevOps'), ('UX', 'UI/UX Design')], default='SE', max_length=2),
        ),
    ]
