# Generated by Django 5.1.3 on 2025-01-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_membroequipe_testearea'),
        ('members', '0004_task_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='area',
        ),
        migrations.AddField(
            model_name='task',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='areatask', to='Users.area'),
        ),
    ]
