# Generated by Django 5.1 on 2025-01-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_task_area_task_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='members.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='vetor_subtasks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
