# Generated by Django 5.1 on 2025-01-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_baseevent_description_alter_baseevent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
