# Generated by Django 5.1 on 2025-01-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
