# Generated by Django 5.1 on 2025-02-09 21:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('flight_success_rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('flight_objective_description', models.TextField()),
                ('results', models.TextField()),
                ('pilot_impressions', models.TextField()),
                ('improvements', models.TextField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wind_direction', models.CharField(max_length=100)),
                ('atmospheric_pressure', models.DecimalField(decimal_places=3, max_digits=5)),
                ('total_takeoff_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flight_cycles', models.PositiveIntegerField()),
                ('telemetry_link', models.URLField()),
                ('occurred_accident', models.BooleanField(default=False)),
                ('pilot_name', models.ManyToManyField(related_name='pilot_flight_logs', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(related_name='team_flight_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('damaged_parts', models.TextField()),
                ('damaged_parts_photo', models.URLField(blank=True, null=True)),
                ('id_flightLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident', to='report.flightlog')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meeting_date', models.DateField()),
                ('meeting_time_begin', models.TimeField()),
                ('meeting_time_end', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('other_participants', models.TextField(blank=True, null=True)),
                ('pauta', models.CharField(blank=True, max_length=255, null=True)),
                ('areas', models.ManyToManyField(to='Users.area')),
                ('responsible', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
