# Generated by Django 5.1 on 2025-02-09 20:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_position_function_priority_value_and_more'),
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentlog',
            name='pilot_flight_count',
        ),
        migrations.RemoveField(
            model_name='accidentlog',
            name='pilot_impressions',
        ),
        migrations.RemoveField(
            model_name='accidentlog',
            name='was_turbulent',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='document_username',
        ),
        migrations.AddField(
            model_name='flightlog',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accidentlog',
            name='damaged_parts_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentlog',
            name='id_flightLog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident', to='report.flightlog'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='atmospheric_pressure',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='flight_success_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='pilot_name',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='team_members',
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='total_takeoff_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meeting_date', models.DateField()),
                ('meeting_time_begin', models.TimeField()),
                ('meeting_time_end', models.TimeField()),
                ('local', models.CharField(max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('other_participants', models.TextField(blank=True, null=True)),
                ('pauta', models.CharField(blank=True, max_length=255, null=True)),
                ('areas', models.ManyToManyField(to='Users.area')),
                ('responsible', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flightlog',
            name='pilot_name',
            field=models.ManyToManyField(related_name='pilot_flight_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='team_members',
            field=models.ManyToManyField(related_name='team_flight_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
