# Generated by Django 5.1.3 on 2025-02-04 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_meeting_link_pauta_meeting_pauta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='responsible',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
