# Generated by Django 5.1.4 on 2025-02-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_flightlog_document_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
