# Generated by Django 5.1.4 on 2025-02-07 03:54

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_flightlog_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlog',
            name='flight_success_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='pilot_name',
            field=models.ManyToManyField(null=True, related_name='pilot_flight_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='team_members',
            field=models.ManyToManyField(null=True, related_name='team_flight_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
