# Generated by Django 5.1.4 on 2025-02-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_flightlog_flight_success_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlog',
            name='pilot_name',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='team_members',
        ),
    ]
