# Generated by Django 5.1.4 on 2025-02-07 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_remove_flightlog_pilot_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='pilot_name',
            field=models.ManyToManyField(related_name='pilot_flight_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='team_members',
            field=models.ManyToManyField(related_name='team_flight_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
