# Generated by Django 5.1.4 on 2025-02-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_flightlog_pilot_name_flightlog_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlog',
            name='pilot_name',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='team_members',
        ),
    ]
