# Generated by Django 5.1.4 on 2025-02-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_flightlog_pilot_name_flightlog_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentlog',
            name='pilot_flight_count',
        ),
        migrations.RemoveField(
            model_name='accidentlog',
            name='pilot_impressions',
        ),
        migrations.RemoveField(
            model_name='accidentlog',
            name='was_turbulent',
        ),
    ]
