# Generated by Django 5.1.4 on 2025-02-08 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_alter_accidentlog_damaged_parts_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentlog',
            name='id_flightLog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident', to='report.flightlog'),
        ),
    ]
