# Generated by Django 5.1.4 on 2025-02-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_alter_flightlog_atmospheric_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlog',
            name='total_takeoff_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
