# Generated by Django 5.1 on 2025-02-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_alter_flightlog_total_takeoff_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='responsible',
        ),
    ]
